# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            奔跑的蜗牛
tagline:          'Keep running'
description:      '记录点滴'
url:              http://blog.arinic.com

author:
  name:           'Arinic'
  url:            http://weibo.com/arinic

paginate:         5

# Custom vars
version:          1.0.0
